---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: pl-create-infra-mcp
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-create-infra-machine-config-pool
      spec:
        namespaceSelector:
          exclude:
          - kube-*
          include:
          - default
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: machineconfiguration.openshift.io/v1
            kind: MachineConfigPool
            metadata:
              name: infra
            spec:
              machineConfigSelector:
                matchExpressions:
                - key: machineconfiguration.openshift.io/role
                  operator: In
                  values:
                  - worker # used for testing
                  - infra
              nodeSelector:
                matchLabels:
                  node-role.kubernetes.io/infra: "" # testing 
        remediationAction: enforce
        severity: low
  remediationAction: inform