{
 "title": "Daniel's Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Operator Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "openshift_kube_scheduler_operator_build_info{cluster=\"$cluster\"}",
     "legendFormat": "kube_scheduler"
    },
    {
     "expr": "openshift_etcd_operator_build_info{cluster=\"$cluster\"}",
     "legendFormat": "etcd_operator"
    },
    {
     "expr": "openshift_apiserver_operator_build_info{cluster=\"$cluster\"}",
     "legendFormat": "apiserver_operator"
    },
    {
     "expr": "openshift_console_operator_build_info{cluster=\"$cluster\"}",
     "legendFormat": "openshift_console"
    },
    {
     "expr": "openshift_kube_apiserver_operator_build_info{cluster=\"$cluster\"}",
     "legendFormat": "kube_apiserver"
    },
    {
     "expr": "openshift_kube_controller_manager_operator_build_info{cluster=\"$cluster\"}",
     "legendFormat": "controller_manager"
    },
    {
     "expr": "openshift_service_ca_operator_build_info{cluster=\"$cluster\"}",
     "legendFormat": "service_ca"
    },
    {
     "expr": "openshift_authentication_operator_build_info{cluster=\"$cluster\"}",
     "legendFormat": "authentication"
    },
    {
     "expr": "openshift_config_operator_build_info{cluster=\"$cluster\"}",
     "legendFormat": "config"
    }
   ]
  },
  {
   "title": "DNS Panic Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_panic_count_total{cluster=\"$cluster\"}[1d]))"
    }
   ]
  },
  {
   "title": "API Error Budget",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-((sum(rate(apiserver_request_total{code=~\"5..\",cluster=\"$cluster\"}[1h]))/sum(rate(apiserver_request_total{cluster=\"$cluster\"}[1h])))/1e-2)"
    }
   ]
  },
  {
   "title": "DNS Response Rate by RCode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_response_rcode_count_total{cluster=\"$cluster\"}[5m])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Etcd Health",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-((sum(rate(etcd_server_health_failures{cluster=\"$cluster\"}[1d]))/sum(rate(etcd_server_health_success{cluster=\"$cluster\"}[1d])))/1e-2)"
    }
   ]
  },
  {
   "title": "Storage Operations",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-((sum(rate(storage_operation_errors_total{cluster=\"$cluster\"}[1d]))/sum(rate(storage_operation_status_count{cluster=\"$cluster\"}[1d])))/1e-2)"
    }
   ]
  },
  {
   "title": "Cluster API 500-Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{code=~\"5..\"}[30m]))/sum(rate(apiserver_request_total[30m]))*100",
     "legendFormat": "Code 500"
    }
   ]
  },
  {
   "title": "API Server Request under 200ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_duration_seconds_bucket{le=\"0.2\",cluster=\"$cluster\"}[5m]))/sum(rate(apiserver_request_duration_seconds_bucket{cluster=\"$cluster\"}[5m]))*100",
     "legendFormat": "Percent"
    }
   ]
  }
 ]
}